### ISSUE TITLE
Automatic check-in fails if /etc/ax25/stat directory has root permissions

### ISSUE THREAD

**Issue by n7nix** [nwdigitalradio/rmsgw#10]

**Comment by n7nix** [comment]
If stat directory has root permissions automatic check-in (rmsgw_aci) will run from crontab & check-in to winlink services instead of the extended period requested by Winlink. Need to set owner:group to rmsgw:rmsgw for /etc/ax25/stat directory. Needs better error display.

**Comment by lisa50469** [comment]
My stat directory is part of the linked /etc/rmsgw structure, and has rmsgw:rmsgw ownership.
When I built rmsgw on Rasp Pi, it places the directory in /usr/local/etc so according to the 'directions' I linked /usr/local/etc/rmsgw to /etc/rmsgw
Seems to be fine.
