### ISSUE TITLE
Failure sending to Winlink.org accounts

### ISSUE THREAD

**Issue by lisa50469** [nwdigitalradio/rmsgw#11]
rmsgw is running perfectly, but if I send a message to a winlink.org account the rmsgw never closes and the message does not get sent.  Sending to Internet e-mail accounts works fine.

root@raspberrypi:~# ./stat
root     30057     1  0 08:35 ?        00:00:00 /usr/sbin/kissattach /dev/ttyUSB0 radio 44.1.2.3
root     30080     1  0 08:35 ?        00:00:00 aprx -l LOG_DAEMON
root     30081 30080  0 08:35 ?        00:00:00 aprx -l LOG_DAEMON
root     30077     1  0 08:35 ?        00:00:00 ax25d
rmsgw    30935 30077  0 08:41 ?        00:00:00 **rmsgw -l debug -P radio AK7WS**

Process 30935 is left over and eventually times out.  But rmsgw no longer will work.

The RMS express session window shows the connection, then the 'Sending' message followed by a considerable delay (~10 seconds) then 'Disconnected'

I have killed all the above processes and restarted them, but rmsgw will still not work.  I have to reboot the Rasp Pi.  Here is my startup script:

root@raspberrypi:~# cat startaprs
echo -e "intface kiss\n\rRESET\n\r" >> /dev/ttyUSB0
sleep 2
/usr/sbin/kissattach /dev/ttyUSB0 radio 44.1.2.3
sleep 2
ax25d
sleep 2
aprx -l LOG_DAEMON

root@raspberrypi:~# uname -a
Linux raspberrypi 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
root@raspberrypi:~#

**Comment by lisa50469** [comment]
After a reboot:  
If I remove the outgoing message in RMS express, rmsgw will continue working.  But only after a Rasp Pi reboot.

**Comment by lisa50469** [comment]
Found something new;  After restarting the Rasp Pi/rmsgw system, the Winlink session worked even with the 'outbox' showing the unsent message.
The connection showed 'Sending 0' and had a normal disconnect and the outbox was then empty.  So this might have more to do with Winlink than rmsgw.  

Although rmsgw did not recover from the issue and had to have a reboot.  It appears that kissattach lingers after this failure.  Possibly another clue.

**Comment by n7nix** [comment]
I don't think this is an RMS Gateway problem. Perhaps you can supply a spy trace (listen -at).

**Comment by n7nix** [comment]
Regarding stats directory having the wrong permissions this has been covered before, see issue "Version Reporting to CMS". It is a requirement that the stats directory is owned by rmsgw:rmsgw otherwise the automatic check-in to Winlink web services does not happen and you will not appear on the Winlink gateway map. It looks like that problem is solved as you are appearing in the Winlink Live System Information packet gateway list.
