### ISSUE TITLE
Executing autogen.sh fails on Debian 7

### ISSUE THREAD

**Issue by computer-wizard** [nwdigitalradio/rmsgw#12]
Executing autogen.sh fails on Debian 7 with:
lib/Makefile.am:3: compiling `fileage.c' with per-target flags requires `AM_PROG_CC_C_O' in `configure.ac'  autoreconf: automake failed with exit status: 1

This can be solved by adding the macro name, AM_PROG_CC_C_O  to the # Check for programs
section of the configuration.ac file.

Boudewijn (Bob) Tenty, VE3TOK

**Comment by ve7fet** [comment]
You know Debian 7 was EOL in 2018, right?

Curious, why are you trying to build it on a deprecated OS that no longer has security patches?


Lee

**Comment by computer-wizard** [comment]
I know that very well Lee but it is for a Ham who is involved with a whole bunch of IRLP /EchoIRLP nodes in the Caribbean, who wants to add RMS/Winlink. These are still running Debian 7  and of course I told them to upgrade numerous times because of the security risk.
Bob
