### ISSUE TITLE
updatesysop.py reports 404

### ISSUE THREAD

**Issue by craigerl** [nwdigitalradio/rmsgw#13]
$ ./updatesysop.py
Posting sysop record update for KM6LYW ...
Found Comments: [22] Special events station
./updatesysop.py *** Sysop update for KM6LYW failed, ErrorCode = 404
Traceback (most recent call last):
  File "./updatesysop.py", line 209, in <module>
    print sys.argv[0] + ' *** Error code:    ' + json_dict['ResponseStatus']['ErrorCode']
TypeError: 'int' object has no attribute '__getitem__'

**Comment by craigerl** [comment]
winlinkservice.xml, need to lose "/status" from the following line,

    <sysopadd paramRoot="SysopAdd">/status/sysop/add</sysopadd>

works, thanks,
-craig

**Comment by n7nix** [comment]
Correct referring to  the README.md in the admin directory:
[admin/README.md](https://github.com/nwdigitalradio/rmsgw/tree/master/admin)
```
The following files in /etc/rmsgw needed to be updated to support V5 Winlink Web Services
winlinkservice.xml
```
All the python files and the winlinkservice.xml & sysop.xml files should be updated to work with V5 Winlink Web Services.
Also you should run updatesysop.py as root
