### ISSUE TITLE
Version Reporting to CMS

### ISSUE THREAD

**Issue by k0qed** [nwdigitalradio/rmsgw#3]
RMS Gateway (v2.5.0) is reporting program version information to the CMS at 30 minute intervals based on logs at the CMS. Version information should be reported approximately every 24 hours. A good approach would be to report this at program startup and then every 24 hours.

**Comment by ve7fet** [comment]
The typical config scripts call for putting a crontab entry in that runs every half an hour, calling rmsgw_aci. All that is supposed to do is run the script. The actual updates to CMS are supposed to be based on the variables in include/rms.h:

<pre>
#define DFLT_VERSIONUPD	86400	/* version updates daily */
#define DFLT_CHANNELUPD	7140	/* channel updates every two hours less one minute */
</pre>

Perhaps rmsgw_aci is broken?

**Comment by n7nix** [comment]
This is an installation problem. Check permissions on /usr/local/etc/rmsgw/stat if the user & group are root:root then the version aging file .version.<callsign-SSID> will never get created and updateversion.py will be run according to the interval set by the crontab entry. The user:group for directory /usr/local/etc/rmsgw/stat needs to be rmsgw:rmsgw
