### ISSUE TITLE
Channel Reporting to CMS

### ISSUE THREAD

**Issue by k0qed** [nwdigitalradio/rmsgw#4]
RMS Gateway (v2.5.0) is reporting channel information to the CMS at 30 minute intervals. Channel data should be reported approximately every 2-3 hours (and no less the every 2 hours). A good approach would be to report all channels at program startup and then every 2 hours.

**Comment by ve7fet** [comment]
The typical config scripts call for putting a crontab entry in that runs every half an hour, calling rmsgw_aci. All that is supposed to do is run the script. The actual updates to CMS are supposed to be based on the variables in include/rms.h:

<pre>
#define DFLT_VERSIONUPD	86400	/* version updates daily */
#define DFLT_CHANNELUPD	7140	/* channel updates every two hours less one minute */
</pre>

Perhaps rmsgw_aci is broken?

**Comment by n7nix** [comment]
This is an installation problem. Check permissions on /usr/local/etc/rmsgw/stat if the user & group are root:root then the channels aging file .channels.<port_name> will never get created and updatechannel.py will be run according to the crontab entry. The user:group for directory /usr/local/etc/rmsgw/stat needs to be rmsgw:rmsgw
