### ISSUE TITLE
rmsgw_aci fails/rmschanstat variable substitution broken

### ISSUE THREAD

**Issue by ve7fet** [nwdigitalradio/rmsgw#6]
rmsgw_aci fails due to variable substitution of @axports@ being broken for rmschanstat (when rmschanstat.in is processed).

This is due to the appropriate variable substitution missing from rmschanstat/Makefile.am

Appropriate sed command needs to be added and tested to ensure it picks up the location of axports from the configure script.

This is the error you get (note there is also an issue with missing the python requests module that is un-related to this issue):
<pre>pi@raspberrypi:/etc/cron.d $ rmsgw_aci
grep: @axports@: No such file or directory
channel vhfdrop unavailable
Traceback (most recent call last):
  File "/etc/rmsgw/updateversion.py", line 37, in <module>
    import requests
ImportError: No module named requests
</pre>

**Comment by n7nix** [comment]
Need advice on when/where these scripts are created sbindir, sysconfdir, prefix, datadir. Otherwise will add:
```
	-e 's|@datadir[@]|\/etc\/ax25\/axports|g'
 ```

**Comment by ve7fet** [comment]
I need to set up a test environment and confirm. Configure tests for the location of the axports file, and should set a define (AXPORTS) based on where it found it. Should be able to use that variable in the substitution. 

I will submit a patch, once I do some test compilations.

**Comment by n7nix** [comment]
Thanks Lee!
