### ISSUE TITLE
Debian packaging rules missing python-requests as a dependency

### ISSUE THREAD

**Issue by ve7fet** [nwdigitalradio/rmsgw#7]
The debian/control file is missing the python-requests package as a dependency.

Without python-requests installed, rmsgw_aci returns an error:
<pre>
pi@raspberrypi:/etc/cron.d $ rmsgw_aci
grep: @axports@: No such file or directory
channel vhfdrop unavailable
Traceback (most recent call last):
  File "/etc/rmsgw/updateversion.py", line 37, in <module>
    import requests
ImportError: No module named requests
</pre>

It can be manually installed to resolve the issue, need to add it to the Depends line.

**Comment by n7nix** [comment]
Thanks.

**Comment by ve7fet** [comment]
Doesn't need it for building (build-depends), only for runtime. So, it should be:

<pre>
Depends: ${shlibs:Depends}, ${misc:Depends}, libax25 (>= 0.0.12), libxml2, python (>=2.7.9), libncurses5, python-requests
</pre>
