### ISSUE TITLE
winlinkservice.xml path for sysopadd incorrect

### ISSUE THREAD

**Issue by ve7fet** [nwdigitalradio/rmsgw#8]
In admin/winlinkservice.xml, the path for the sysopadd api is incorrect.

Current path is /status/sysop/add, the correct location is /sysop/add.

The bad path throws a 404 error when updatesysop.py is run:
<pre>
./updatesysop.py *** Sysop update for N0CALL failed, ErrorCode = 404
Traceback (most recent call last):
  File "./updatesysop.py", line 209, in <module>
    print sys.argv[0] + ' *** Error code:    ' + json_dict['ResponseStatus']['ErrorCode']
TypeError: 'int' object has no attribute '__getitem__'
</pre>

**Comment by n7nix** [comment]
Thanks.
